<?php
/**
 * ACF field group registration for Projects.
 *
 * @package AshaduzzamanPortfolio
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Register ACF local field group for project post type.
 *
 * @return void
 */
function ashp_register_project_acf_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key' => 'group_ashp_projects',
			'title' => 'Project Fields',
			'fields' => array(
				array(
					'key' => 'field_ashp_project_type',
					'label' => 'Project Type',
					'name' => 'project_type',
					'type' => 'text',
					'instructions' => 'Project type or category, e.g. Web App, Landing Page.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_ashp_technologies',
					'label' => 'Technology',
					'name' => 'built_with',
					'type' => 'text',
					'instructions' => 'Comma-separated list of technologies used for the project.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'React, Tailwind, WordPress',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_ashp_live_link',
					'label' => 'Live Link',
					'name' => 'live_link',
					'type' => 'url',
					'instructions' => 'URL to the live project website.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'https://example.com',
				),
				array(
					'key' => 'field_ashp_github_link',
					'label' => 'Github Link',
					'name' => 'github_link',
					'type' => 'url',
					'instructions' => 'URL to the project repository.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'https://github.com/example/repo',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'project',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => 'Fields used by the React frontend for project data.',
		)
	);

	acf_add_local_field_group(
		array(
			'key' => 'group_ashp_home_page',
			'title' => 'Home Page',
			'fields' => array(
				array(
					'key' => 'field_ashp_home_tab_hero',
					'label' => 'Hero Section',
					'name' => '',
					'type' => 'tab',
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_ashp_hero_availability',
					'label' => 'Availability',
					'name' => 'availability',
					'type' => 'text',
					'instructions' => 'Availability status text to show in the hero section.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Available for hire',
				),
				array(
					'key' => 'field_ashp_hero_title',
					'label' => 'Hero Title',
					'name' => 'hero_title',
					'type' => 'text',
					'instructions' => 'Main hero title.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Hello, I am...',
				),
				array(
					'key' => 'field_ashp_hero_sub_title',
					'label' => 'Sub Title',
					'name' => 'sub_title',
					'type' => 'text',
					'instructions' => 'Sub title below the hero title.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Frontend Developer and Designer',
				),
				array(
					'key' => 'field_ashp_hero_content',
					'label' => 'Hero Content',
					'name' => 'hero_content',
					'type' => 'wysiwyg',
					'instructions' => 'Formatted hero content for the homepage.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
				),
				array(
					'key' => 'field_ashp_upwork_link',
					'label' => 'Upwork Link',
					'name' => 'upwork_link',
					'type' => 'url',
					'instructions' => 'Link to Upwork profile or job page.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'https://www.upwork.com',
				),
				array(
					'key' => 'field_ashp_fiverr_link',
					'label' => 'Fiverr Link',
					'name' => 'fiverr_link',
					'type' => 'url',
					'instructions' => 'Link to Fiverr profile or gig.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'https://www.fiverr.com',
				),
				array(
					'key' => 'field_ashp_freelancer_link',
					'label' => 'Freelancer Link',
					'name' => 'freelancer_link',
					'type' => 'url',
					'instructions' => 'Link to Freelancer profile or project.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'https://www.freelancer.com',
				),
				array(
					'key' => 'field_ashp_booking_link',
					'label' => 'Booking Link',
					'name' => 'booking_link',
					'type' => 'url',
					'instructions' => 'Link for booking or consultation.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'https://calendly.com/your-profile',
				),
				array(
					'key' => 'field_ashp_resume_upload',
					'label' => 'Resume Upload',
					'name' => 'resume_upload',
					'type' => 'file',
					'instructions' => 'Upload your resume file.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'pdf,doc,docx',
				),
				array(
					'key' => 'field_ashp_hero_picture',
					'label' => 'Picture',
					'name' => 'picture',
					'type' => 'image',
					'instructions' => 'Hero image for the homepage.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg,png,svg',
				),
				array(
					'key' => 'field_ashp_home_tab_about',
					'label' => 'About Section',
					'name' => '',
					'type' => 'tab',
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_ashp_about_section_title',
					'label' => 'Section Title',
					'name' => 'section_title',
					'type' => 'text',
					'instructions' => 'The title for the About section.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'About Me',
				),
				array(
					'key' => 'field_ashp_about_highlight_title',
					'label' => 'Highlight Title',
					'name' => 'highlight_title',
					'type' => 'text',
					'instructions' => 'A short title or highlight for the About section.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Why choose me',
				),
				array(
					'key' => 'field_ashp_about_me',
					'label' => 'About Me',
					'name' => 'about_me',
					'type' => 'wysiwyg',
					'instructions' => 'Main About Me content for the homepage.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
				),
				array(
					'key' => 'field_ashp_home_tab_services',
					'label' => 'Services Section',
					'name' => '',
					'type' => 'tab',
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_ashp_service_item_1',
					'label' => 'Service Item 1',
					'name' => 'service_item_1',
					'type' => 'group',
					'instructions' => 'Service item 1 for the About section.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_ashp_service_1_icon',
							'label' => 'Icon',
							'name' => 'icon',
							'type' => 'image',
							'instructions' => 'Icon for service item 1.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg,png,svg',
						),
						array(
							'key' => 'field_ashp_service_1_number',
							'label' => 'Service Number',
							'name' => 'number_of_serve',
							'type' => 'text',
							'instructions' => 'Number or label for service item 1.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '100+',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_ashp_service_1_title',
							'label' => 'Service Title',
							'name' => 'title_of_service',
							'type' => 'text',
							'instructions' => 'Title for service item 1.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '75',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Web Development',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						)
					)
				),
				array(
					'key' => 'field_ashp_service_item_2',
					'label' => 'Service Item 2',
					'name' => 'service_item_2',
					'type' => 'group',
					'instructions' => 'Service item 2 for the About section.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_ashp_service_2_icon',
							'label' => 'Icon',
							'name' => 'icon',
							'type' => 'image',
							'instructions' => 'Icon for service item 2.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg,png,svg',
						),
						array(
							'key' => 'field_ashp_service_2_number',
							'label' => 'Service Number',
							'name' => 'number_of_serve',
							'type' => 'text',
							'instructions' => 'Number or label for service item 2.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '100+',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_ashp_service_2_title',
							'label' => 'Service Title',
							'name' => 'title_of_service',
							'type' => 'text',
							'instructions' => 'Title for service item 2.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '75',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Web Development',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						)
					)
				),
				array(
					'key' => 'field_ashp_service_item_3',
					'label' => 'Service Item 3',
					'name' => 'service_item_3',
					'type' => 'group',
					'instructions' => 'Service item 3 for the About section.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_ashp_service_3_icon',
							'label' => 'Icon',
							'name' => 'icon',
							'type' => 'image',
							'instructions' => 'Icon for service item 3.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg,png,svg',
						),
						array(
							'key' => 'field_ashp_service_3_number',
							'label' => 'Service Number',
							'name' => 'number_of_serve',
							'type' => 'text',
							'instructions' => 'Number or label for service item 3.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '100+',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_ashp_service_3_title',
							'label' => 'Service Title',
							'name' => 'title_of_service',
							'type' => 'text',
							'instructions' => 'Title for service item 3.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '75',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Web Development',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						)
					)
				),
				array(
					'key' => 'field_ashp_service_item_4',
					'label' => 'Service Item 4',
					'name' => 'service_item_4',
					'type' => 'group',
					'instructions' => 'Service item 4 for the About section.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_ashp_service_4_icon',
							'label' => 'Icon',
							'name' => 'icon',
							'type' => 'image',
							'instructions' => 'Icon for service item 4.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg,png,svg',
						),
						array(
							'key' => 'field_ashp_service_4_number',
							'label' => 'Service Number',
							'name' => 'number_of_serve',
							'type' => 'text',
							'instructions' => 'Number or label for service item 4.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '100+',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_ashp_service_4_title',
							'label' => 'Service Title',
							'name' => 'title_of_service',
							'type' => 'text',
							'instructions' => 'Title for service item 4.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '75',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Web Development',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						)
					)
				)
			),
			'location' => array(
				array(
					array(
						'param' => 'page',
						'operator' => '==',
						'value' => '12',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => 'Fields used by the React frontend for project data.',
		)
	);
}

add_action( 'acf/init', 'ashp_register_project_acf_fields' );
